version: "3.2"

services:
  api:
    build: .
    image: docker-compose-go
    container_name: 'go-docker'
    ports:
    - "8080:8081"
    
  nginx:
    image: "nginx"
    ports:
    - "8083:80"
    links:
    - api
  

